-- Extend club_benefits table with missing fields needed for ClubSector UI
ALTER TABLE public.club_benefits
  ADD COLUMN IF NOT EXISTS discount_text TEXT,
  ADD COLUMN IF NOT EXISTS address TEXT,
  ADD COLUMN IF NOT EXISTS phone TEXT,
  ADD COLUMN IF NOT EXISTS website TEXT,
  ADD COLUMN IF NOT EXISTS sector TEXT NOT NULL DEFAULT '';

-- Seed data from ClubSector.tsx hardcoded discounts
-- Sector: deporte
INSERT INTO public.club_benefits (partner_name, description, discount_text, address, phone, website, sector, category, is_active, priority) VALUES
  ('FitZaragoza', 'Gimnasio completo con piscina climatizada y sauna. Acceso 24/7.', '20% descuento', 'Calle Alfonso I, 23', '976 123 456', NULL, 'deporte', 'deporte', true, 10),
  ('Gym Campus', 'Especializado en crossfit y entrenamiento funcional.', '15% + matrícula gratis', 'Av. San José, 45', '976 234 567', NULL, 'deporte', 'deporte', true, 9),
  ('Yoga Studio Zen', 'Clases de yoga, pilates y meditación. Horarios flexibles.', 'Primera clase gratis', 'Calle Heroísmo, 8', '976 345 678', NULL, 'deporte', 'deporte', true, 8),
  ('Running Club ZGZ', 'Club de running con entrenamientos grupales y carreras.', 'Inscripción gratuita', 'Parque Grande', NULL, 'www.runningclubzgz.es', 'deporte', 'deporte', true, 7),
  ('CrossFit Box Aragón', 'Box de CrossFit con coaches certificados.', '30% primer mes', 'Polígono Cogullada, 12', '976 456 789', NULL, 'deporte', 'deporte', true, 6),
  ('Decathlon Campus', 'Tienda de deportes con amplia variedad de material.', '10% en todo', 'Puerto Venecia', '976 567 890', NULL, 'deporte', 'deporte', true, 5),
  ('Pádel Indoor', 'Pistas de pádel cubiertas con clases particulares.', '2x1 en alquiler pistas', 'Calle María Moliner, 56', '976 678 901', NULL, 'deporte', 'deporte', true, 4),
  ('Natación Club', 'Piscina olímpica con cursos de natación.', '25% abono mensual', 'CDM Alberto Maestro', '976 789 012', NULL, 'deporte', 'deporte', true, 3),
  ('Sprinter Sports', 'Tienda especializada en running y fitness.', '15% en ropa deportiva', 'Gran Casa', '976 890 123', NULL, 'deporte', 'deporte', true, 2),
  ('Escalada Vertical', 'Rocódromo indoor con rutas para todos los niveles.', '50% primera sesión', 'Av. Navarra, 34', '976 901 234', NULL, 'deporte', 'deporte', true, 1),
-- Sector: material
  ('Copistería Campus', 'Impresión, encuadernación y material de oficina. Servicio rápido 24h.', '15% descuento', 'Calle Pedro Cerbuna, 8', '976 567 890', NULL, 'material', 'material', true, 10),
  ('PrintShop Express', 'Especialistas en trabajos universitarios y TFG.', '20% encuadernaciones', 'Plaza San Francisco, 15', '976 678 901', NULL, 'material', 'material', true, 9),
  ('Librería Pórtico', 'Librería especializada en manuales universitarios.', '10% libros texto', 'Calle Costa, 4', '976 789 012', NULL, 'material', 'material', true, 8),
  ('Papelería Central', 'Todo tipo de material de papelería y escritura.', '15% material oficina', 'Paseo Independencia, 23', '976 890 123', NULL, 'material', 'material', true, 7),
  ('Digital Print 24h', 'Impresión gran formato y planos arquitectónicos.', 'Ploteo desde 2€', 'Calle Zurita, 12', '976 901 234', NULL, 'material', 'material', true, 6),
  ('Casa del Libro', 'Gran selección de libros académicos y literatura.', '5% socios estudiantes', 'Paseo Sagasta, 45', '976 012 345', NULL, 'material', 'material', true, 5),
  ('Fnac Zaragoza', 'Tablets, portátiles y accesorios tecnológicos.', '10% electrónica estudio', 'Plaza España', '976 123 456', NULL, 'material', 'material', true, 4),
  ('Copy Rapid', 'Servicio de copias económico y rápido.', 'Copias B/N 0.02€', 'Calle Doctor Cerrada, 8', '976 234 567', NULL, 'material', 'material', true, 3),
  ('Abacus', 'Material de bellas artes y manualidades.', '15% material arte', 'Calle Alfonso I, 17', '976 345 678', NULL, 'material', 'material', true, 2),
  ('Tecno-Campus', 'Reparación de dispositivos y accesorios.', 'Reparación móvil 20% dto', 'Calle San Miguel, 22', '976 456 789', NULL, 'material', 'material', true, 1),
-- Sector: restauracion
  ('Café Estudiantil', 'Menús diarios y bocadillos. WiFi gratis y zona de estudio.', '10% descuento', 'Calle Universidad, 34', '976 789 012', NULL, 'restauracion', 'restauracion', true, 10),
  ('La Taverna', 'Comida casera mediterránea. Menú diario variado.', '2x1 menú del día', 'Calle Don Jaime, 56', '976 890 123', NULL, 'restauracion', 'restauracion', true, 9),
  ('Pizza Campus', 'Pizzas artesanales con ingredientes frescos.', '15% para llevar', 'Calle San Vicente, 12', '976 901 234', NULL, 'restauracion', 'restauracion', true, 8),
  ('Sushi Go', 'Sushi fresco con servicio a domicilio.', '20% pedidos online', 'Paseo Constitución, 8', NULL, 'www.sushigo.es', 'restauracion', 'restauracion', true, 7),
  ('Brunch & Co', 'Brunch americano y tartas caseras.', 'Café gratis con desayuno', 'Calle Manifestación, 23', '976 012 345', NULL, 'restauracion', 'restauracion', true, 6),
  ('Kebab Palace', 'Kebabs y falafel auténticos.', 'Bebida gratis con menú', 'Calle Conde Aranda, 45', '976 123 456', NULL, 'restauracion', 'restauracion', true, 5),
  ('Burger Lab', 'Hamburguesas artesanales con ingredientes premium.', '15% hamburguesas gourmet', 'Calle Temple, 7', '976 234 567', NULL, 'restauracion', 'restauracion', true, 4),
  ('Wok Express', 'Cocina asiática rápida y económica.', '10% menú estudiante', 'Av. Goya, 34', '976 345 678', NULL, 'restauracion', 'restauracion', true, 3),
  ('Heladería Gino', 'Helados artesanales italianos.', '2x1 helados (L-J)', 'Plaza del Pilar, 12', '976 456 789', NULL, 'restauracion', 'restauracion', true, 2),
  ('Veggie Corner', 'Restaurante vegano con opciones saludables.', '15% menú vegano', 'Calle Mayor, 28', '976 567 890', NULL, 'restauracion', 'restauracion', true, 1),
-- Sector: transporte
  ('BikeZGZ', 'Alquiler de bicicletas y patinetes. Plan mensual sin compromiso.', '25% primer mes', 'Calle Costa, 12', NULL, 'www.bikezgz.es', 'transporte', 'transporte', true, 10),
  ('StudentPass', 'Abono mensual para estudiantes en toda la red de transporte público.', '20% abono transporte', 'Online', NULL, 'www.transportezaragoza.es', 'transporte', 'transporte', true, 9),
  ('Lime Scooters', 'Patinetes eléctricos de alquiler por minutos.', '3 viajes gratis', 'App móvil', NULL, 'www.li.me', 'transporte', 'transporte', true, 8),
  ('BlaBlaCar', 'Compartir coche para viajes interurbanos.', '10% primer viaje', 'Online', NULL, 'www.blablacar.es', 'transporte', 'transporte', true, 7),
  ('Cabify', 'Servicio de VTC con tarifas fijas.', '5€ descuento código UNIZAR', 'App móvil', NULL, 'www.cabify.com', 'transporte', 'transporte', true, 6),
  ('Taller Bici Campus', 'Taller especializado en reparación de bicicletas.', '15% reparaciones', 'Calle San Jorge, 8', '976 678 901', NULL, 'transporte', 'transporte', true, 5),
  ('Gasolinera Repsol Campus', 'Descuento en combustible para estudiantes.', '3 ctms/litro', 'Av. Academia, 1', '976 789 012', NULL, 'transporte', 'transporte', true, 4),
  ('Parking Centro', 'Parking céntrico con plazas para motos y coches.', '30% abono mensual', 'Plaza España (subterráneo)', '976 890 123', NULL, 'transporte', 'transporte', true, 3),
  ('Renfe Joven', 'Descuentos en billetes de tren para menores de 26.', 'Tarjeta Joven 25% dto', 'Estación Delicias', NULL, 'www.renfe.com', 'transporte', 'transporte', true, 2),
  ('AutoRent Zaragoza', 'Alquiler de coches económicos.', '15% alquiler fin semana', 'Av. Navarra, 89', '976 901 234', NULL, 'transporte', 'transporte', true, 1),
-- Sector: moda
  ('H&M Campus', 'Moda joven y accesorios a precios asequibles.', '10% con carné estudiante', 'Paseo Independencia, 11', '976 123 456', NULL, 'moda', 'moda', true, 10),
  ('Vintage Store', 'Tienda de ropa vintage y retro seleccionada.', '15% ropa segunda mano', 'Calle Contamina, 5', '976 234 567', NULL, 'moda', 'moda', true, 9),
  ('Sneakers Lab', 'Tienda especializada en sneakers y streetwear.', '10% zapatillas', 'Calle Alfonso I, 32', '976 345 678', NULL, 'moda', 'moda', true, 8),
  ('Pull&Bear', 'Moda urbana y casual para jóvenes.', 'Acceso ventas privadas', 'Gran Casa', '976 456 789', NULL, 'moda', 'moda', true, 7),
  ('Mango Outlet', 'Moda con descuentos permanentes.', '20% adicional outlet', 'Puerto Venecia', '976 567 890', NULL, 'moda', 'moda', true, 6),
  ('Foot Locker', 'Las mejores marcas de calzado deportivo.', '15% calzado deportivo', 'Gran Casa', '976 678 901', NULL, 'moda', 'moda', true, 5),
  ('Parfois', 'Bolsos, bisutería y complementos de moda.', '2x1 en accesorios', 'Paseo Independencia, 24', '976 789 012', NULL, 'moda', 'moda', true, 4),
  ('Bershka', 'Moda joven y tendencias actuales.', '10% primera compra', 'Centro Comercial', '976 890 123', NULL, 'moda', 'moda', true, 3),
  ('Calzedonia', 'Medias, calcetines y ropa interior.', '3x2 en calcetines', 'Paseo Sagasta, 17', '976 901 234', NULL, 'moda', 'moda', true, 2),
  ('Kiabi', 'Moda económica para toda la familia.', '15% ropa familiar', 'Puerto Venecia', '976 012 345', NULL, 'moda', 'moda', true, 1),
-- Sector: servicios
  ('Lavandería Express', 'Servicio de lavandería autoservicio y a domicilio.', '10% descuento', 'Calle Heroísmo, 12', '976 345 678', NULL, 'servicios', 'servicios', true, 10),
  ('WashClub', 'Lavandería moderna con WiFi gratis y zona de espera.', '2x1 lavado + secado', 'Paseo Independencia, 89', '976 456 789', NULL, 'servicios', 'servicios', true, 9),
  ('Peluquería Trends', 'Peluquería unisex con estilistas profesionales.', '20% corte estudiante', 'Calle San Miguel, 15', '976 567 890', NULL, 'servicios', 'servicios', true, 8),
  ('Barber Shop Classic', 'Barbería tradicional con productos premium.', '15% servicios', 'Calle Temple, 8', '976 678 901', NULL, 'servicios', 'servicios', true, 7),
  ('Centro Estética Luna', 'Tratamientos faciales y corporales.', '25% primera visita', 'Calle Alfonso I, 45', '976 789 012', NULL, 'servicios', 'servicios', true, 6),
  ('Tintorería Rápida', 'Tintorería con servicio express en 24h.', '15% limpieza en seco', 'Calle Doctor Cerrada, 23', '976 890 123', NULL, 'servicios', 'servicios', true, 5),
  ('Cerrajería 24h', 'Servicio de cerrajería urgente.', '10% estudiantes', 'Calle Mayor, 56', '976 901 234', NULL, 'servicios', 'servicios', true, 4),
  ('Clínica Dental Campus', 'Clínica dental con precios especiales para estudiantes.', 'Primera revisión gratis', 'Av. Goya, 12', '976 012 345', NULL, 'servicios', 'servicios', true, 3),
  ('Óptica Universitaria', 'Óptica con amplio catálogo de monturas.', '30% gafas graduadas', 'Paseo Sagasta, 34', '976 123 456', NULL, 'servicios', 'servicios', true, 2),
  ('Farmacia Central', 'Farmacia 24h con productos de parafarmacia.', '5% parafarmacia', 'Plaza España, 2', '976 234 567', NULL, 'servicios', 'servicios', true, 1),
-- Sector: ocio
  ('Oasis Club', 'Jueves universitarios con música comercial.', 'Entrada gratis', 'Calle Temple, 25', '976 345 678', NULL, 'ocio', 'ocio', true, 10),
  ('La Casa del Loco', 'Pub universitario con ambiente alternativo.', '2x1 antes 00:00', 'Plaza San Francisco, 8', '976 456 789', NULL, 'ocio', 'ocio', true, 9),
  ('Bóveda Club', 'Discoteca con música electrónica y sesiones especiales.', '50% entrada', 'Calle Boggiero, 28', '976 567 890', NULL, 'ocio', 'ocio', true, 8),
  ('Cotton Club', 'Miércoles de estudiantes con copas a 4€.', 'Entrada gratis', 'Av. Cesaraugusto, 15', '976 678 901', NULL, 'ocio', 'ocio', true, 7),
  ('The Blackbird', 'Pub irlandés con música en vivo.', 'Cerveza artesana 2€', 'Calle Temple, 12', '976 789 012', NULL, 'ocio', 'ocio', true, 6),
  ('Sala López', 'Sala de conciertos con artistas nacionales e internacionales.', '15% conciertos', 'Calle López Ibor, 5', NULL, 'www.salalopez.com', 'ocio', 'ocio', true, 5),
  ('Cines Palafox', 'Cine céntrico con últimos estrenos.', 'Miércoles 5€', 'Calle Independencia, 12', '976 890 123', NULL, 'ocio', 'ocio', true, 4),
  ('Bolera Bowling', 'Bolera con bar y zona arcade.', 'Partida 3€ (L-J)', 'Puerto Venecia', '976 901 234', NULL, 'ocio', 'ocio', true, 3),
  ('Escape Room ZGZ', 'Salas de escape con diferentes temáticas.', '20% grupos estudiantes', 'Calle Manifestación, 45', '976 012 345', NULL, 'ocio', 'ocio', true, 2),
  ('Karaoke Star', 'Karaoke con salas privadas y catálogo amplio.', 'Sala privada 15€/h', 'Calle San Vicente, 34', '976 123 456', NULL, 'ocio', 'ocio', true, 1),
-- Sector: tecnologia
  ('Apple Store (Fnac)', 'Productos Apple con condiciones especiales para estudiantes.', 'Financiación 0% TAE', 'Plaza España', '976 234 567', NULL, 'tecnologia', 'tecnologia', true, 10),
  ('MediaMarkt', 'Gran superficie de electrónica y electrodomésticos.', '5% extra con carné', 'Puerto Venecia', '976 345 678', NULL, 'tecnologia', 'tecnologia', true, 9),
  ('PC Componentes', 'Tienda online de componentes y periféricos.', 'Envío gratis +50€', 'Online', NULL, 'www.pccomponentes.com', 'tecnologia', 'tecnologia', true, 8),
  ('Phone House', 'Móviles y accesorios de todas las marcas.', '10% accesorios', 'Gran Casa', '976 456 789', NULL, 'tecnologia', 'tecnologia', true, 7),
  ('Repair Tech', 'Reparación de smartphones y tablets.', '15% reparación móvil', 'Calle San Miguel, 28', '976 567 890', NULL, 'tecnologia', 'tecnologia', true, 6),
  ('Game Zaragoza', 'Tienda especializada en videojuegos y consolas.', '10% videojuegos', 'Paseo Independencia, 34', '976 678 901', NULL, 'tecnologia', 'tecnologia', true, 5),
  ('CoolMod', 'Tienda de componentes gaming y overclocking.', '5% componentes PC', 'Online + recogida', NULL, 'www.coolmod.com', 'tecnologia', 'tecnologia', true, 4),
  ('Worten', 'Electrónica de consumo y electrodomésticos.', 'Garantía extendida gratis', 'Centro Comercial Augusta', '976 789 012', NULL, 'tecnologia', 'tecnologia', true, 3),
  ('iFixit Partner', 'Herramientas y kits para reparar tus dispositivos.', '20% kits reparación', 'Online', NULL, 'www.ifixit.com', 'tecnologia', 'tecnologia', true, 2),
  ('Streaming Bundle', 'Pack especial streaming para estudiantes.', 'Spotify + HBO 7.99€', 'Online', NULL, 'www.spotify.com/student', 'tecnologia', 'tecnologia', true, 1)
ON CONFLICT DO NOTHING;
